using Draco.Compiler.Api.Semantics;
using Draco.Compiler.Internal.Types;

namespace Draco.Compiler.Internal.Symbols.Synthetized;

/// <summary>
/// A local generated by the compiler.
/// </summary>
internal sealed class SynthetizedLocalSymbol : LocalSymbol
{
    public override Type Type { get; }
    public override bool IsMutable => throw new System.NotImplementedException();
    public override Symbol? ContainingSymbol => throw new System.NotImplementedException();

    public SynthetizedLocalSymbol(Type type)
    {
        this.Type = type;
    }

    public override ISymbol ToApiSymbol() => throw new System.NotImplementedException();
}
