using System;

namespace Draco.Compiler.Internal.Symbols.Synthetized;

/// <summary>
/// A label generated by the compiler.
/// </summary>
internal sealed class SynthetizedLabelSymbol : LabelSymbol
{
    public override string Name { get; }
    public override Symbol? ContainingSymbol => throw new NotImplementedException();

    public SynthetizedLabelSymbol(string name)
    {
        this.Name = name;
    }

    public override Api.Semantics.ISymbol ToApiSymbol() => new Api.Semantics.LabelSymbol(this);
}
