using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Draco.Compiler.Internal.Symbols.Synthetized;

/// <summary>
/// Represents the "this" parameter of a function generated by the compiler.
/// </summary>
internal sealed class SynthetizedThisParameterSymbol : ParameterSymbol
{
    public override FunctionSymbol ContainingSymbol { get; }
    public override TypeSymbol Type => (TypeSymbol)this.ContainingSymbol.ContainingSymbol!;
    public override string Name => "this";
    public override bool IsThis => true;

    public SynthetizedThisParameterSymbol(FunctionSymbol containingSymbol)
    {
        this.ContainingSymbol = containingSymbol;
    }
}
