# Deploy to GH pages the Blazor Web Editor.

name: 'Deploy Blazor Web Editor to GH Pages'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Clone the repo
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Cache Blazor Build Output
      uses: actions/cache@v3
      with:
        path: src/Draco.Editor.Web/build/
        key: blazor # Yes the key is constant.
    - name: Run tests
      run: dotnet test ./src
    - name: Publish with dotnet
      working-directory: 'src/Draco.Editor.Web'
      run: dotnet publish --configuration Release --output build
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.4
      with:
        path: 'src/Draco.Editor.Web/build/wwwroot'
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.2
