# Publish everything to NuGet

name: 'Publish packages'

on:
  release:
    types: [published]

env:
  DOTNET_VERSION: '7.0.x'   # The .NET SDK version to use
  CONFIGURATION: 'Release'  # The configuration to use
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
  VSC_MARKETPLACE_TOKEN: ${{ secrets.VSC_MARKETPLACE_TOKEN }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  deploy-sdk-and-langserver:
    runs-on: windows-latest
    steps:
      # Set up environment
    - name: Clone the repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

      # Build and packaging
    - name: Package
      run: |
        cd src
        dotnet restore .
        dotnet build . --configuration ${{ env.CONFIGURATION }} --no-restore
        dotnet pack . /p:PackageReleaseNotes="See https://github.com/Draco-lang/Compiler/releases/tag/${{ env.RELEASE_TAG }}"

      # Publishing
    - name: Upload to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: ./**/*.nupkg

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./**/*.nupkg

    - name: Upload to NuGet.org
      run: dotnet nuget push ./**/*.nupkg --api-key ${{ env.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --no-symbols

  deploy-vsc-extension:
    runs-on: windows-latest
    steps:
      # Set up environment
    - name: Clone the repo
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 18

    - name: Install VSCE
      run: npm install -g @vscode/vsce

      # Build and packaging
    - name: Package
      run: |
        cd src/Draco.Extension.VsCode
        npm install
        vsce package

      # Publishing
    - name: Upload to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: ./**/*.vsix

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./**/*.vsix

    - name: Upload to VS Code Marketplace
      run: vsce publish --pat ${{ env.VSC_MARKETPLACE_TOKEN }}
