# Publish everything to NuGet

name: 'Publish packages'

on:
  release:
    types: [published]

env:
  DOTNET_VERSION: '7.0.x'   # The .NET SDK version to use
  CONFIGURATION: 'Release'  # The configuration to use
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  deploy-sdk-and-langserver:
    runs-on: windows-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 18

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build ./src --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Package
      run: dotnet pack ./src /p:PackageReleaseNotes="See https://github.com/Draco-lang/Compiler/releases/tag/${{ RELEASE_TAG }}"

    - name: Upload to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: Draco
        path: src/**/*${{ RELEASE_TAG }}.nupkg

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: src/**/*${{ RELEASE_TAG }}.nupkg

    - name: Upload to NuGet.org
      run: dotnet nuget push src/**/*${{ RELEASE_TAG }}.nupkg --api-key ${{ env.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --no-symbols

  deploy-vsc-extension:
    runs-on: windows-latest
    steps:
    - name: Clone the repo
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 18

    - name: Install VSCE
      run: npm install -g @vscode/vsce

    - name: Navigate into extension folder
      run: cd .src/Draco.Extension.VsCode

    - name: Install dependencies
      run: npm install

    - name: Package extension
      run: vsce package

    - name: Upload to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: Draco.VscExtension
        path: ./**/*.vsix

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./**/*.vsix

    - name: Publish extension
      run: vsce publish
