# Checks that the current branch passes all tests

name: Mutation Testing

on:
  workflow_dispatch:
  push:
    paths:
    - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/**'

env:
  DOTNET_VERSION: '7.0.x'   # The .NET SDK version to use
  CONFIGURATION: 'Release'  # The configuration to use
  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

jobs:
  tests:
    name: mutation-testing-ubuntu-latest

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dotnet tools
      run: dotnet tool restore

    - name: Install dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build ./src --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Run Mutation Testing
      run: dotnet stryker --reporter "dashboard" --with-baseline:${{ github.base_ref }} --version ${{ github.head_ref }}
