# Checks that the current branch passes all tests

name: tests

on:
  workflow_dispatch:
  push:
    paths:
    - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/**'

env:
  DOTNET_VERSION: '6.0.x'   # The .NET SDK version to use
  CONFIGURATION: 'Release'  # The configuration to use

jobs:
  tests:
    name: tests-${{matrix.os}}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Run tests
      run: dotnet test --no-build
